services:
  app:
    image: <IMAGEMDOALUNO>
    container_name: <NOMEDOCONTAINERDOALUNO>
    ports:
      - "<PORTADOALUNO>:3000"
    environment:
      DB_HOST: dbcentral
      DB_USER: root
      DB_PASS: password
      DB_NAME: <bancodoaluno>
networks:
  rede_alunos:
    external: true

