services:
  app:
    image: jenrique138/app:staging
    container_name: <NOMEDOCONTAINERDOALUNO>
    ports:
      - "<PORTADOALUNO>:3000"
    environment:
      DB_HOST: mysql-infra
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: <bancodoaluno>
    networks:
      - rede_alunos
networks:
  rede_alunos:
    external: true

