name: integracao continua

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  estagio_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Node.js 18
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Verificar inicialização do projeto
        run: node --check index.js
